Implement helm chart and skaffold setup
gardener/gardener-discovery-server pull request #19
Opened 2024-05-09 08:59 UTC by dimityrmirchev

**What this PR does / why we need it**:
Implements helm chart and skaffold setup.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user
NONE
```

2024-05-09 09:00 UTC, dimityrmirchev commented
/kind enhancement

2024-05-15 09:20 UTC, vpnachev requested changes
Very nice, just some minor nits.

2024-05-15 09:20 UTC, vpnachev commented on charts/discovery-server/charts/runtime/templates/deployment.yaml
> +        - name: http
```suggestion
        - name: https
```

2024-05-15 09:20 UTC, vpnachev commented on charts/discovery-server/charts/runtime/templates/service.yaml
> +  - name: http
```suggestion
  - name: https
```

2024-05-15 09:37 UTC, dimityrmirchev commented on charts/discovery-server/charts/runtime/templates/deployment.yaml
> +        checksum/gardener-discovery-server-kubeconfig: {{ include (print $.Template.BasePath "/secret-kubeconfig.yaml") . | sha256sum }}
Whoops. I somehow forgot that. Thanks for noticing

2024-05-15 11:05 UTC, vpnachev commented
/lgtm
/approve

2024-05-15 11:06 UTC, merged